# Generated by Django 3.1.2 on 2020-12-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='usuario',
            field=models.ManyToManyField(to='dashboard.Usuario'),
        ),
    ]
