# Generated by Django 3.1.2 on 2020-12-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_categoria_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_est', models.CharField(max_length=30)),
                ('endereco_est', models.CharField(max_length=120)),
                ('telefone_est', models.CharField(max_length=11)),
                ('descricao_est', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='estabelecimento',
            field=models.ManyToManyField(to='dashboard.Estabelecimento'),
        ),
    ]
