# Generated by Django 3.1.2 on 2020-12-03 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201203_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('imagem', models.ImageField(upload_to='')),
                ('comentario', models.CharField(max_length=240)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.FloatField()),
                ('voucher', models.ImageField(upload_to='')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.estabelecimento')),
                ('usuario', models.ManyToManyField(to='dashboard.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('data', models.DateField()),
                ('comentario', models.CharField(max_length=240)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.estabelecimento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuario')),
            ],
        ),
    ]
