# Generated by Django 3.1.2 on 2020-12-07 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20201207_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comentario',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuario'),
        ),
    ]
