# Generated by Django 3.1.2 on 2020-12-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20201208_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='primeiro_nome',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='ultimo_nome',
            new_name='twitter',
        ),
    ]
