# Generated by Django 3.1.2 on 2020-12-10 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_auto_20201210_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='usuario',
        ),
        migrations.AddField(
            model_name='categoria',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
