# Generated by Django 3.1.2 on 2020-12-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20201210_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pontuacao',
            field=models.IntegerField(null=True),
        ),
    ]
